[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
KMeansClustering = "8091de74-9783-440e-837f-a649ce4f6ee7"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
TSne = "24678dba-d5e9-5843-a4c6-250288b04835"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"

[compat]
DataFrames = "1.6"
Documenter = "1.5"
MLJ = "0.20"
Plots = "1.40"
